package org.campagnelab.metar.R.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class Identifier_Constraints extends BaseConstraintsDescriptor {
  public Identifier_Constraints() {
    super(MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x55b5a4eee04b52b7L));
  }
}
