package org.campagnelab.metar.R.editor;

/*Generated by MPS */

import jetbrains.mps.lang.editor.generator.internal.AbstractCellMenuComponent;
import jetbrains.mps.nodeEditor.cellMenu.SubstituteInfoPartExt;

public class ExprMenuComponent extends AbstractCellMenuComponent {
  public ExprMenuComponent() {
    super(new SubstituteInfoPartExt[]{});
  }
}
