package org.campagnelab.ANTLR.behavior;

/*Generated by MPS */


public class Alternatives_BehaviorDescriptor extends ParserRuleBlock_BehaviorDescriptor {
  public Alternatives_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR.structure.Alternatives";
  }
}
