package org.campagnelab.ANTLR.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LexerRuleRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public LexerRuleRef_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR.structure.LexerRuleRef";
  }
}
