package org.campagnelab.ANTLR.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public abstract class ParserRuleBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements ToTextOutput_BehaviorDescriptor {
  public ParserRuleBlock_BehaviorDescriptor() {
  }
  public String virtual_toText_5668935624399900127(SNode thisNode) {
    return ParserRuleBlock_Behavior.virtual_toText_5668935624399900127(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR.structure.ParserRuleBlock";
  }
}
