package org.campagnelab.ANTLR.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ParserRule_BehaviorDescriptor extends Rule_BehaviorDescriptor implements ToTextOutput_BehaviorDescriptor {
  public ParserRule_BehaviorDescriptor() {
  }
  public String virtual_toText_5668935624399900127(SNode thisNode) {
    return ParserRule_Behavior.virtual_toText_5668935624399900127(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR.structure.ParserRule";
  }
}
