package org.campagnelab.ANTLR.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Rule_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Rule_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR.structure.Rule";
  }
}
