package org.campagnelab.ANTLR.behavior;

/*Generated by MPS */


public class StringLiteral_BehaviorDescriptor extends LexerToken_BehaviorDescriptor {
  public StringLiteral_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR.structure.StringLiteral";
  }
}
