package org.campagnelab.ANTLR.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface ToTextOutput_BehaviorDescriptor {
  public String virtual_toText_5668935624399900127(SNode thisNode);
}
