package org.campagnelab.BigDataScript;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.ILanguageAspect;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import jetbrains.mps.smodel.runtime.StructureAspectDescriptor;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "a567e729-b95b-4c8d-9948-9653643918cd(org.campagnelab.BigDataScript)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "org.campagnelab.BigDataScript";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("a567e729-b95b-4c8d-9948-9653643918cd"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "476e0657-0158-41ee-a854-9fbc8f5a004b(org.campagnelab.BigDataScript#4220331111870013486)"));
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    if (aspectClass == EditorAspectDescriptor.class) {
      return ((T) new EditorAspectDescriptorBase());
    }
    if (aspectClass == StructureAspectDescriptor.class) {
      return (T) new org.campagnelab.BigDataScript.structure.StructureAspectDescriptor();
    }
    return super.createAspect(aspectClass);
  }
}
