package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ErrorStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public ErrorStatement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ErrorStatement";
  }
}
