package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Expression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Expression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.Expression";
  }
}
