package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionSysExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionSysExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionSysExpression";
  }
}
