package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionVariableInitImplicitExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionVariableInitImplicitExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionVariableInitImplicitExpression";
  }
}
