package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionAssignmentMultExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionAssignmentMultExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionAssignmentMultExpression";
  }
}
