package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionLogicAndExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionLogicAndExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionLogicAndExpression";
  }
}
