package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionBitNegationExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionBitNegationExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionBitNegationExpression";
  }
}
