package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionBitAndExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionBitAndExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionBitAndExpression";
  }
}
