package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionCondExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionCondExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionCondExpression";
  }
}
