package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionParallelExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionParallelExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionParallelExpression";
  }
}
