package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionBitOrExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionBitOrExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionBitOrExpression";
  }
}
