package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionDepOperatorExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionDepOperatorExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionDepOperatorExpression";
  }
}
