package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionUnaryPlusExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionUnaryPlusExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionUnaryPlusExpression";
  }
}
