package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionParenExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionParenExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionParenExpression";
  }
}
