package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ExpressionDepExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ExpressionDepExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ExpressionDepExpression";
  }
}
