package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ForLoopStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public ForLoopStatement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ForLoopStatement";
  }
}
