package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class FunctionCallExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public FunctionCallExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.FunctionCallExpression";
  }
}
