package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class IfStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public IfStatement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.IfStatement";
  }
}
