package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class LiteralListEmptyExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public LiteralListEmptyExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.LiteralListEmptyExpression";
  }
}
