package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class LiteralMapEmptyExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public LiteralMapEmptyExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.LiteralMapEmptyExpression";
  }
}
