package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class LiteralIntExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public LiteralIntExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.LiteralIntExpression";
  }
}
