package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class LiteralListExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public LiteralListExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.LiteralListExpression";
  }
}
