package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class ReturnStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public ReturnStatement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.ReturnStatement";
  }
}
