package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class StatementIncludeStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public StatementIncludeStatement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.StatementIncludeStatement";
  }
}
