package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class StatmentEolStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public StatmentEolStatement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.StatmentEolStatement";
  }
}
