package org.campagnelab.BigDataScript.behavior;

/*Generated by MPS */


public class VarReferenceListExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public VarReferenceListExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.BigDataScript.structure.VarReferenceListExpression";
  }
}
