package org.campagnelab.ANTLR45.behavior;

/*Generated by MPS */


public class DocCommentGrammarSpec_BehaviorDescriptor extends LexerElement_BehaviorDescriptor {
  public DocCommentGrammarSpec_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR45.structure.DocCommentGrammarSpec";
  }
}
