package org.campagnelab.ANTLR45.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Rules_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Rules_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR45.structure.Rules";
  }
}
