package org.campagnelab.ANTLR45.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class RuleSpec_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public RuleSpec_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.ANTLR45.structure.RuleSpec";
  }
}
