package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ChildDestination_BehaviorDescriptor extends Destination_BehaviorDescriptor {
  public ChildDestination_BehaviorDescriptor() {
  }
  public String virtual_name_2860118060023810449(SNode thisNode) {
    return ChildDestination_Behavior.virtual_name_2860118060023810449(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.antlr.tomps.structure.ChildDestination";
  }
}
