package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ConceptMapper_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ConceptMapper_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.antlr.tomps.structure.ConceptMapper";
  }
}
