package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.Language;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ConceptMapper_Behavior {
  public static Language call_language_7627187573640578145(SNode __thisNode__) {
    return ConceptMapper__BehaviorDescriptor.language_id6BpdF0a7Ghx(__thisNode__);
  }
  public static SNode call_converter_558881339892985529(SNode __thisNode__) {
    return ConceptMapper__BehaviorDescriptor.converter_idv1yTSnUAUT(__thisNode__);
  }
  public static SNode call_visitorReturnConcept_558881339892987079(SNode __thisNode__) {
    return ConceptMapper__BehaviorDescriptor.visitorReturnConcept_idv1yTSnUBj7(__thisNode__);
  }
  public static SNode call_grammar_558881339893016520(SNode __thisNode__) {
    return ConceptMapper__BehaviorDescriptor.grammar_idv1yTSnUIv8(__thisNode__);
  }
  public static SNode call_looupOrCreate_1826877622988453211(SAbstractConcept __thisConcept__, Language language, String name) {
    return ConceptMapper__BehaviorDescriptor.looupOrCreate_id1_qnSjmlzlr(__thisConcept__, language, name);
  }
  public static SNode call_looupOrCreate_1826877622988760384(SNode __thisNode__, String name) {
    return ConceptMapper__BehaviorDescriptor.looupOrCreate_id1_qnSjmmIl0(__thisNode__, name);
  }
  public static SNode call_createConcept_558881339898873634(SAbstractConcept __thisConcept__, Language language, String name) {
    return ConceptMapper__BehaviorDescriptor.createConcept_idv1yTSoh4sy(__thisConcept__, language, name);
  }
  public static Iterable<SNode> call_altMappers_558881339902034843(SNode __thisNode__) {
    return ConceptMapper__BehaviorDescriptor.altMappers_idv1yTSot8er(__thisNode__);
  }
  public static boolean call_hasLabels_8933086517772846254(SNode __thisNode__) {
    return ConceptMapper__BehaviorDescriptor.hasLabels_id7JSGHIZFCiI(__thisNode__);
  }
  public static String call_upperCaseFirstChar_4917522066818939248(SNode __thisNode__, String value) {
    return ConceptMapper__BehaviorDescriptor.upperCaseFirstChar_id4gYz4fZSN_K(__thisNode__, value);
  }
  public static void call_createEditorFor_1849555336877531523(SNode __thisNode__, SNode concept, SNode alternative, SNode altMapper) {
    ConceptMapper__BehaviorDescriptor.createEditorFor_id1AEWcuf0Q63(__thisNode__, concept, alternative, altMapper);
  }
  public static void call_createEditors_1849555336877441106(SNode __thisNode__) {
    ConceptMapper__BehaviorDescriptor.createEditors_id1AEWcuf0w1i(__thisNode__);
  }
  public static SNode call_cellModel_1849555336878701510(SNode __thisNode__, SNode alternative, SNode altMapper) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcuf5jJ6(__thisNode__, alternative, altMapper);
  }
  public static SNode call_cellModel_1849555336878833409(SNode __thisNode__, SNode block, SNode altMapper) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcuf5NW1(__thisNode__, block, altMapper);
  }
  public static SNode call_cellModel_1849555336879372042(SNode __thisNode__, SNode ruleRef, SNode altMapper) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcuf7Rsa(__thisNode__, ruleRef, altMapper);
  }
  public static SNode call_cellModel_1849555336887504686(SNode __thisNode__, SNode ruleRef, SNode altMapper) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcufASWI(__thisNode__, ruleRef, altMapper);
  }
  public static SNode call_cellModel_1849555336879378070(SNode __thisNode__, SNode literal, SNode altMapper) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcuf7SUm(__thisNode__, literal, altMapper);
  }
  public static SNode call_cellModel_1849555336886703143(SNode __thisNode__, SNode labeledElement, SNode altMapper) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcufzPgB(__thisNode__, labeledElement, altMapper);
  }
  public static SNode call_cellModel_1849555336880419944(SNode __thisNode__, SNode sequence, SNode altMapper) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcufbRhC(__thisNode__, sequence, altMapper);
  }
  public static SNode call_cellModel_1849555336880416531(SNode __thisNode__, SNode literal) {
    return ConceptMapper__BehaviorDescriptor.cellModel_id1AEWcufbQsj(__thisNode__, literal);
  }
  public static void call_createTextGenFor_4522383332274891725(SNode __thisNode__, SNode concept, SNode alternative, SNode altMapper) {
    ConceptMapper__BehaviorDescriptor.createTextGenFor_id3V2IUSqp6Jd(__thisNode__, concept, alternative, altMapper);
  }
  public static void call_createTextGens_4522383332274891802(SNode __thisNode__) {
    ConceptMapper__BehaviorDescriptor.createTextGens_id3V2IUSqp6Kq(__thisNode__);
  }
  public static Tuples._2<SNode, String> call_findDestination_4522383332277190979(SAbstractConcept __thisConcept__, SNode altMapper, String ruleRefName) {
    return ConceptMapper__BehaviorDescriptor.findDestination_id3V2IUSqxS53(__thisConcept__, altMapper, ruleRefName);
  }
}
