package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Destination_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Destination_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.antlr.tomps.structure.Destination";
  }
}
