package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class Destination_Behavior {
  public static void init(SNode thisNode) {
  }
}
