package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class LexerRuleSource_BehaviorDescriptor extends Source_BehaviorDescriptor {
  public LexerRuleSource_BehaviorDescriptor() {
  }
  public String virtual_name_4068410015138152876(SNode thisNode) {
    return LexerRuleSource_Behavior.virtual_name_4068410015138152876(thisNode);
  }
  public SNode virtual_parserObject_4068410015138622604(SNode thisNode) {
    return LexerRuleSource_Behavior.virtual_parserObject_4068410015138622604(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.antlr.tomps.structure.LexerRuleSource";
  }
}
