package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Mapper_Behavior {
  public static SNode call_alternative_558881339903204669(SNode __thisNode__) {
    return Mapper__BehaviorDescriptor.alternative_idv1yTSox_OX(__thisNode__);
  }
  public static SNode call_concept_558881339903199920(SNode __thisNode__) {
    return Mapper__BehaviorDescriptor.concept_idv1yTSox$EK(__thisNode__);
  }
  public static void call_linkDeclarationsForConceptInterface_4068410015139836194(SNode __thisNode__, List<SNode> links, SNode concept) {
    Mapper__BehaviorDescriptor.linkDeclarationsForConceptInterface_id3xPTlDT3j4y(__thisNode__, links, concept);
  }
  public static void call_someMethod_6247096756516935321(SNode __thisNode__) {
    Mapper__BehaviorDescriptor.someMethod_id5qM9mr9FXqp(__thisNode__);
  }
  public static List<SNode> call_linkDeclarations_4068410015139474010(SNode __thisNode__, SNode concept) {
    return Mapper__BehaviorDescriptor.linkDeclarations_id3xPTlDT1UDq(__thisNode__, concept);
  }
  public static void call_propertyDeclarationsForConceptInterface_2860118060023510633(SNode __thisNode__, List<SNode> properties, SNode concept) {
    Mapper__BehaviorDescriptor.propertyDeclarationsForConceptInterface_id2uLbzznonpD(__thisNode__, properties, concept);
  }
  public static List<SNode> call_propertyDeclarations_2860118060023510679(SNode __thisNode__, SNode concept) {
    return Mapper__BehaviorDescriptor.propertyDeclarations_id2uLbzznonqn(__thisNode__, concept);
  }
}
