package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class NewVisitor_BehaviorDescriptor extends Expression_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.antlr.tomps.structure.NewVisitor";
  }

}
