package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.Language;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Operator_Behavior {
  public static SNode call_converter_1826877622986928160(SNode __thisNode__) {
    return Operator__BehaviorDescriptor.converter_id1_qnSjmfJ0w(__thisNode__);
  }
  public static SNode call_looupOrCreate_1826877622986925758(SNode __thisNode__, String name) {
    return Operator__BehaviorDescriptor.looupOrCreate_id1_qnSjmfIqY(__thisNode__, name);
  }
  public static void call_createTextGen_4522383332287859149(SNode __thisNode__, Language language) {
    Operator__BehaviorDescriptor.createTextGen_id3V2IUSra$Bd(__thisNode__, language);
  }
}
