package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ToIntDestination_BehaviorDescriptor extends Destination_BehaviorDescriptor {
  public ToIntDestination_BehaviorDescriptor() {
  }
  public String virtual_name_2860118060023810449(SNode thisNode) {
    return ToIntDestination_Behavior.virtual_name_2860118060023810449(thisNode);
  }
  public SNode virtual_to_1096804516885006638(SNode thisNode) {
    return ToIntDestination_Behavior.virtual_to_1096804516885006638(thisNode);
  }
  public SNode virtual_type_6247096756518626823(SNode thisNode) {
    return ToIntDestination_Behavior.virtual_type_6247096756518626823(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.antlr.tomps.structure.ToIntDestination";
  }
}
