package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ToOperator_BehaviorDescriptor extends Destination_BehaviorDescriptor {
  public SNode virtual_cellModel_1849555336881449838(SNode __thisNode__, String cardinality) {
    return null;
  }
  public String virtual_name_2860118060023810449(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_textGenAppendPart_4522383332277577012(SNode __thisNode__, String cardinality) {
    return null;
  }
  public SNode virtual_to_1096804516885006638(SNode __thisNode__) {
    return null;
  }
  public SNode virtual_type_6247096756518626823(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.antlr.tomps.structure.ToOperator";
  }

}
