package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class AndExpr_BehaviorDescriptor extends BinaryOperatorExpr_BehaviorDescriptor {
  public AndExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.AndExpr";
  }
}
