package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class AssignToTheRight_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public AssignToTheRight_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.AssignToTheRight";
  }
}
