package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class AssignmentOperator_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public AssignmentOperator_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.AssignmentOperator";
  }
}
