package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class BodyExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public BodyExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.BodyExpr";
  }
}
