package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class Colon_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public Colon_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.Colon";
  }
}
