package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class ComparisonExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public ComparisonExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.ComparisonExpr";
  }
}
