package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public abstract class ComparisonOperator_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public ComparisonOperator_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.ComparisonOperator";
  }
}
