package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class Difference_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public Difference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.Difference";
  }
}
