package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class Division_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public Division_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.Division";
  }
}
