package org.campagnelab.metar.R.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Dollar_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Dollar_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.Dollar";
  }
}
