package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class DollarExpr_BehaviorDescriptor extends BinaryOperatorExpr_BehaviorDescriptor {
  public DollarExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.DollarExpr";
  }
}
