package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class ExprSub_BehaviorDescriptor extends Parameter_BehaviorDescriptor {
  public ExprSub_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.ExprSub";
  }
}
