package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class FloatLiteralExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public FloatLiteralExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.FloatLiteralExpr";
  }
}
