package org.campagnelab.metar.R.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ForcefulAssignment_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ForcefulAssignment_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.ForcefulAssignment";
  }
}
