package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class ForExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public ForExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.ForExpr";
  }
}
