package org.campagnelab.metar.R.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class GreaterThan_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public GreaterThan_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.GreaterThan";
  }
}
