package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class IdExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public IdExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.IdExpr";
  }
}
