package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class IfElseExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public IfElseExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.IfElseExpr";
  }
}
