package org.campagnelab.metar.R.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Minus_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Minus_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.Minus";
  }
}
