package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class MultiplicationExpr_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public MultiplicationExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.MultiplicationExpr";
  }
}
