package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class NAExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public NAExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.NAExpr";
  }
}
