package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class Not_BehaviorDescriptor extends UnaryOperator_BehaviorDescriptor {
  public Not_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.Not";
  }
}
