package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class OrExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public OrExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.OrExpr";
  }
}
