package org.campagnelab.metar.R.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Parameters_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Parameters_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.Parameters";
  }
}
