package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public abstract class RightAssignmentOperator_BehaviorDescriptor extends AssignmentOperator_BehaviorDescriptor {
  public RightAssignmentOperator_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.RightAssignmentOperator";
  }
}
