package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class StringExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public StringExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.StringExpr";
  }
}
