package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class STRINGSub_BehaviorDescriptor extends Parameter_BehaviorDescriptor {
  public STRINGSub_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.STRINGSub";
  }
}
