package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class TildeExpr_BehaviorDescriptor extends BinaryOperatorExpr_BehaviorDescriptor {
  public TildeExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.TildeExpr";
  }
}
