package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class USER_OPExpr_BehaviorDescriptor extends BinaryOperator_BehaviorDescriptor {
  public USER_OPExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.USER_OPExpr";
  }
}
