package org.campagnelab.metar.R.behavior;

/*Generated by MPS */


public class UserOpExpr_BehaviorDescriptor extends Expr_BehaviorDescriptor {
  public UserOpExpr_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.structure.UserOpExpr";
  }
}
