package org.campagnelab.metar.R.functions.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FormalParameters_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FormalParameters_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.functions.structure.FormalParameters";
  }
}
