package org.campagnelab.metar.R.functions.behavior;

/*Generated by MPS */


public class VarargsFormalParameter_BehaviorDescriptor extends FormalParameter_BehaviorDescriptor {
  public VarargsFormalParameter_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.R.functions.structure.VarargsFormalParameter";
  }
}
