package org.campagnelab.ANTLR.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionAspectBase;
import jetbrains.mps.intentions.IntentionFactory;
import org.jetbrains.annotations.Nullable;
import java.util.Collection;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.Arrays;

public final class IntentionsDescriptor extends IntentionAspectBase {
  private final long[] myId2Index;
  private IntentionFactory[] myIntentions0;
  private IntentionFactory[] myIntentions1;
  private IntentionFactory[] myIntentions2;

  public IntentionsDescriptor() {
    myId2Index = new long[3];
    myId2Index[0] = 0x631eebe3113222a9L;
    myId2Index[1] = 0x631eebe31132d838L;
    myId2Index[2] = 0x631eebe31132d843L;
  }

  @Override
  @Nullable
  public Collection<IntentionFactory> getIntentions(@NotNull SConceptId conceptId) {
    final int index = Arrays.binarySearch(myId2Index, conceptId.getIdValue());
    switch (index) {
      case 0:
        // Concept: Grammar 
        if (myIntentions0 == null) {
          myIntentions0 = new IntentionFactory[1];
          myIntentions0[0] = new ClearAll_Intention();
        }
        return Arrays.asList(myIntentions0);
      case 1:
        // Concept: ParserRule 
        if (myIntentions1 == null) {
          myIntentions1 = new IntentionFactory[1];
          myIntentions1[0] = new LabelAllAlternatives_Intention();
        }
        return Arrays.asList(myIntentions1);
      case 2:
        // Concept: ParserRuleBlock 
        if (myIntentions2 == null) {
          myIntentions2 = new IntentionFactory[2];
          myIntentions2[0] = new AddLabel_Intention();
          myIntentions2[1] = new DefineLabel_Intention();
        }
        return Arrays.asList(myIntentions2);
      default:
        return null;
    }
  }

  @NotNull
  @Override
  public Collection<IntentionFactory> getAllIntentions() {
    IntentionFactory[] rv = new IntentionFactory[4];
    rv[0] = new ClearAll_Intention();
    rv[1] = new AddLabel_Intention();
    rv[2] = new LabelAllAlternatives_Intention();
    rv[3] = new DefineLabel_Intention();
    return Arrays.asList(rv);
  }
}
