package org.campagnelab.metar.R.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAtom = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.Atom", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x69d936b00a2fce6fL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptBinaryOperationExpr = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.BinaryOperationExpr", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x4aaf5f3861bb6069L)).super_("org.campagnelab.metar.R.structure.Expr").super_(MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1866cbeaL)).parents("org.campagnelab.metar.R.structure.Expr").parentIds(MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1866cbeaL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(5381624775493511113L, "operator")).properties("operator").create();
  /*package*/ final ConceptDescriptor myConceptExpr = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.Expr", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1866cbeaL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(4068410015139835205L, "superConcept", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x69d936b00a2fce6fL), true, false, false)).children(new String[]{"superConcept"}, new boolean[]{false}).create();
  /*package*/ final ConceptDescriptor myConceptFormlist = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.Formlist", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1882ed98L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptFunctionExpr = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.FunctionExpr", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e18703190L)).super_("org.campagnelab.metar.R.structure.Expr").super_(MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1866cbeaL)).parents("org.campagnelab.metar.R.structure.Expr").parentIds(MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1866cbeaL)).childDescriptors(new ConceptDescriptorBuilder.Link(558881339902982178L, "params", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1882f824L), false, true, false)).children(new String[]{"params"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptIfExpr = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.IfExpr", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e187d2ab4L)).super_("org.campagnelab.metar.R.structure.Expr").super_(MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1866cbeaL)).parents("org.campagnelab.metar.R.structure.Expr").parentIds(MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1866cbeaL)).childDescriptors(new ConceptDescriptorBuilder.Link(4068410015139835215L, "b", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x69d936b00a2fce6fL), true, false, false)).children(new String[]{"b"}, new boolean[]{false}).create();
  /*package*/ final ConceptDescriptor myConceptParameter = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.Parameter", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x7c18b9e1882f824L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptProg = new ConceptDescriptorBuilder("org.campagnelab.metar.R.structure.Prog", MetaIdFactory.conceptId(0x3b58810c84314bbbL, 0x99eab4671e02dd13L, 0x3979b6603a37b961L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAtom, myConceptBinaryOperationExpr, myConceptExpr, myConceptFormlist, myConceptFunctionExpr, myConceptIfExpr, myConceptParameter, myConceptProg);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0m, conceptFqName)) {
      case 0:
        return myConceptAtom;
      case 1:
        return myConceptBinaryOperationExpr;
      case 2:
        return myConceptExpr;
      case 3:
        return myConceptFormlist;
      case 4:
        return myConceptFunctionExpr;
      case 5:
        return myConceptIfExpr;
      case 6:
        return myConceptParameter;
      case 7:
        return myConceptProg;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0m = new String[]{"org.campagnelab.metar.R.structure.Atom", "org.campagnelab.metar.R.structure.BinaryOperationExpr", "org.campagnelab.metar.R.structure.Expr", "org.campagnelab.metar.R.structure.Formlist", "org.campagnelab.metar.R.structure.FunctionExpr", "org.campagnelab.metar.R.structure.IfExpr", "org.campagnelab.metar.R.structure.Parameter", "org.campagnelab.metar.R.structure.Prog"};
}
